### ISSUE TITLE
No parameterless constructor defined for type 'System.String'.

### ISSUE THREAD

**Issue by PavelYzhakov** [mrxten/db-request-filters#28]
Reproduce:
1) Create `TreeFilter` model with `Value` of type `string`
Example json:
```
{
    "Where":
    {
        "OperatorType":0,
        "Operands":[
            {
                "OperatorType":0,
                "Field":"Name",
                "FilterType":1,
                "Value":"Comp"
            }
        ]
    },
    "Skip":0,
    "Take":20
}
```
2) Run `.Where()` with this model
3) Exception `No parameterless constructor defined for type 'System.String'.`
StackTrace:
```
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at QueryDesignerCore.Expressions.WhereExpression.TryCastFieldValueType(Object value, Type type)
   at QueryDesignerCore.Expressions.WhereExpression.GenerateExpressionOneField(Expression prop, WhereFilter filter)
   at QueryDesignerCore.Expressions.WhereExpression.GetExpressionForField(Expression e, WhereFilter filter, String suffix)
   at QueryDesignerCore.Expressions.WhereExpression.GetExpressionForTreeField(Expression e, TreeFilter filter, String suffix)
   at QueryDesignerCore.Expressions.WhereExpression.GetTreeExpression[T](TreeFilter filter, String suffix)
   at QueryDesignerCore.QueryableExtensions.Where[T](IQueryable`1 query, TreeFilter filter)
```

Looks like exception throws [here](https://github.com/mrxten/QueryDesigner/blob/8f0d3da054d0998836857ffaf221c0b0fca2b2f8/src/QueryDesignerCore/Expressions/WhereExpression.cs#L364) when trying it with `string` type.

**Comment by PavelYzhakov** [comment]
Nevermind, issue was in json deserialization.
